### ISSUE TITLE
error while trying to export .aar and .bin

### ISSUE THREAD

**Issue by Glaedorf** [priverop/JUSToolkit#11]
Hi !
When i Try to export aar file i have an unhandled exception "The specified argument was not within the range of valid values"
![Error AAR](https://user-images.githubusercontent.com/88801083/129279845-a0876003-7727-4427-89fe-bceefd060c58.png)

And when i try to export bin file i have an unhandled exception too "An exception was thrown by the target of a call. ---> System.Collections.Generic.KeyNotFoundException: The given key was missing from the dictionary."
![Error BIN](https://user-images.githubusercontent.com/88801083/129280159-281ea08d-e865-4ba9-9a22-9aca70cd85fd.png)

These are the files i tried to export
[envoi.zip](https://github.com/priverop/JUSToolkit/files/6978910/envoi.zip)

Thanks for your help if you read !

**Comment by Darkc0m** [comment]
Hello, I am unable to find those files inside the game but I can tell you that for the .bin one it's not going to work.

Most of the game files have that extension but are very different from one another. A very important thing to keep in mind is that this tool is being worked on with translation purposes in mind (maybe we should specify it on the readme) so it only works with the .bin files that contain text. That's why when the tool tries to identify a .bin file it looks up the name of it and takes the type of format from a dictionary (yours isn't so the tool can't find the key).

As for the .aar one I can't exacly tell you what's going on because the export and import code for that format was made by @priverop, so I'll try to ask him about it. 

You can add me on discord if you want so you can explain better to me what you are trying to do. `Darkc0m#9723`

**Comment by priverop** [comment]
Hey @Glaedorf do you still need help with this? We just revamped the entire tool and now it's way easier to use. But where are these files from? Are they from Jump Ultimate Stars?

**Comment by priverop** [comment]
Please feel free to open a new issue
